function import_forcecurve = importforcecurve(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  DAY14OPCDRGFVV1HZMYE2FORCECURVEINDEX12 = IMPORTFILE1(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  DAY14OPCDRGFVV1HZMYE2FORCECURVEINDEX12 = IMPORTFILE1(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  day14OPCDRGFVv1Hzmye2ForceCurveIndex12 = importfile1("C:\Users\ME System 3\Documents\projects\OL DRG coculture\manuscript figures\force curve data\day14_OPC_DRG_FV_v1Hz_mye-2_ForceCurveIndex_12.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Aug-2021 12:19:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["s", "nN"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
import_forcecurve = readtable(filename, opts);

end